apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-hello-world-container
  labels:
    app: java-hello-world-container
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-hello-world-container
  template:
    metadata:
      labels:
        app: java-hello-world-container
    spec:
      containers:
        - name: java-hello-world-container
          image: java-hello-world:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: INTERVAL_SECONDS
              value: "10"
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
