apiVersion: kargo.akuity.io/v1alpha1
kind: ProjectConfig
metadata:
  name: java-hello-world-container-project
  namespace: java-hello-world-container-project
spec:
  promotionPolicies:
    - stageSelector:
        name: dev
      autoPromotionEnabled: true
