apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: dev
  namespace: java-hello-world-container-project
spec:
  requestedFreight:
    - origin:
        kind: Warehouse
        name: java-hello-world-container-warehouse
      sources:
        direct: true
  promotionTemplate:
    spec:
      vars:
        - name: gitRepo
          value: https://github.com/TonyHsieh/java-hello-world-container.git
        - name: imageRepo
          value: solidstrider/java-hello-world-container
      steps:
        # 1. Clone the repository
        - uses: git-clone
          config:
            repoURL: ${{ vars.gitRepo }}
            checkout:
              - branch: main
                path: ./src

        # 2. Update the image in kustomization.yaml
        - uses: kustomize-set-image
          config:
            path: ./src/gitops/overlays/dev
            images:
              - image: java-hello-world
                newName: ${{ vars.imageRepo }}
                tag: ${{ imageFrom(vars.imageRepo).Tag }}

        # 3. Commit the changes
        - uses: git-commit
          config:
            path: ./src
            message: "Promote image to ${{ imageFrom(vars.imageRepo).Tag }} [skip ci]"

        # 4. Push the changes
        - uses: git-push
          config:
            path: ./src
            targetBranch: main
