apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: java-hello-world
  newName: solidstrider/java-hello-world-container
  newTag: 577f12e452f26f965c6b1a74c456d2a9d95f51fd
