apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

images:
- name: java-hello-world
  newName: solidstrider/java-hello-world-container
  newTag: a208dd456121b3e5cfd8a5fadf19a073b645c9f5
