apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: java-hello-world
  newName: solidstrider/java-hello-world-container
  newTag: 9b8facd7714bdcab669ee77204988770861ec367
